// Copyright(c) 2024 Agora.io. All rights reserved.

#pragma once


#pragma region UABT_ENUM_CONVERT

#pragma region Original Example

//static inline agora::rtc::AUDIO_MIXING_REASON_TYPE ToRawValue(EUABT_AUDIO_MIXING_REASON_TYPE Val) {
//    agora::rtc::AUDIO_MIXING_REASON_TYPE Result; 
//    
//    switch (Val) {
//        case EUABT_AUDIO_MIXING_REASON_TYPE::AUDIO_MIXING_REASON_OK: 
//            Result = agora::rtc::AUDIO_MIXING_REASON_TYPE::AUDIO_MIXING_REASON_OK;
//            break; 
//        default: 
//            Result = agora::rtc::AUDIO_MIXING_REASON_TYPE::AUDIO_MIXING_REASON_OK;
//            break;
//    } 
//    
//    return Result;
//}
//
//static inline EUABT_AUDIO_MIXING_REASON_TYPE WrapWithUE(agora::rtc::AUDIO_MIXING_REASON_TYPE Val) {
//
//    EUABT_AUDIO_MIXING_REASON_TYPE Result; 
//    
//    switch (Val) {
//        case agora::rtc::AUDIO_MIXING_REASON_TYPE::AUDIO_MIXING_REASON_OK: 
//            Result = EUABT_AUDIO_MIXING_REASON_TYPE::AUDIO_MIXING_REASON_OK;
//            break; 
//        default: 
//            Result = EUABT_AUDIO_MIXING_REASON_TYPE::AUDIO_MIXING_REASON_OK; 
//            break;
//    } 
//    
//    return Result;
//}

#pragma endregion Original Example


// Method: Convert [UEEnum] to [RawEnum]
#define FUNCNAME_ToRawValue ToRawValue
// Method: Convert [RawEnum] to [UEEnum]
#define FUNCNAME_ToUEEnum WrapWithUE

// Notice
// 1. The first item would be the default value

#pragma region Base

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL) \
    static inline RAW_ENUM_TYPE FUNCNAME_ToRawValue(UEBP_ENUM_TYPE Val) { \
            RAW_ENUM_TYPE Result;\
            switch(Val){\
                case UEBP_ENUM_TYPE::DEFAULT_ENUM_VAL: Result = RAW_ENUM_TYPE::DEFAULT_ENUM_VAL; break;

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL) \
        default:\
			Result = RAW_ENUM_TYPE::DEFAULT_ENUM_VAL;\
			break;\
            }\
        return Result; \
    }\
    static inline UEBP_ENUM_TYPE FUNCNAME_ToUEEnum(RAW_ENUM_TYPE Val) { \
    		UEBP_ENUM_TYPE Result;\
            switch(Val){\
                 case RAW_ENUM_TYPE::DEFAULT_ENUM_VAL: Result = UEBP_ENUM_TYPE::DEFAULT_ENUM_VAL; break;

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_BASEINNER_BOTTOM(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL) \
        default:\
			Result = UEBP_ENUM_TYPE::DEFAULT_ENUM_VAL;\
			break;\
            }\
        return Result; \
    }

#pragma endregion Base


#pragma region UABTEnumConversion 1 Entry - Default Entry

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_1_ENTRY(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL)\
    GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL)\
    GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL)\
    GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_BASEINNER_BOTTOM(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL)

#pragma endregion UABTEnumConversion 1 Entry - Default Entry



#pragma region UABTEnumConversion 2 Entries

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_2_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02)\
    GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL)\
        case UEBP_ENUM_TYPE::ENUM_VAL02: Result = RAW_ENUM_TYPE::ENUM_VAL02; break;

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_2_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL)\
	    case RAW_ENUM_TYPE::ENUM_VAL02: Result = UEBP_ENUM_TYPE::ENUM_VAL02; break;


#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_2_ENTRIES(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_2_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02)\
    GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_2_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_BASEINNER_BOTTOM(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL)

#pragma endregion UABTEnumConversion 2 Entries

#pragma region UABTEnumConversion 3 Entries

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_3_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03)\
    GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_2_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02)\
    		case UEBP_ENUM_TYPE::ENUM_VAL03: Result = RAW_ENUM_TYPE::ENUM_VAL03; break;

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_3_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_2_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02)\
	    case RAW_ENUM_TYPE::ENUM_VAL03: Result = UEBP_ENUM_TYPE::ENUM_VAL03; break;

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_3_ENTRIES(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_3_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_3_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_BASEINNER_BOTTOM(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL)

#pragma endregion UABTEnumConversion 3 Entries


#pragma region UABTEnumConversion 4 Entries

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_4_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_3_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03)\
			case UEBP_ENUM_TYPE::ENUM_VAL04: Result = RAW_ENUM_TYPE::ENUM_VAL04; break;

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_4_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_3_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03)\
		case RAW_ENUM_TYPE::ENUM_VAL04: Result = UEBP_ENUM_TYPE::ENUM_VAL04; break;

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_4_ENTRIES(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_4_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_4_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_BASEINNER_BOTTOM(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL)

#pragma endregion UABTEnumConversion 4 Entries


#pragma region UABTEnumConversion 5 Entries

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_5_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_4_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04)\
			case UEBP_ENUM_TYPE::ENUM_VAL05: Result = RAW_ENUM_TYPE::ENUM_VAL05; break;

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_5_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_4_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04)\
		case RAW_ENUM_TYPE::ENUM_VAL05: Result = UEBP_ENUM_TYPE::ENUM_VAL05; break;


#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_5_ENTRIES(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_5_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_5_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_BASEINNER_BOTTOM(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL)

#pragma endregion UABTEnumConversion 5 Entries


#pragma region UABTEnumConversion 6 Entries

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_6_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_5_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05)\
			case UEBP_ENUM_TYPE::ENUM_VAL06: Result = RAW_ENUM_TYPE::ENUM_VAL06; break;

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_6_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_5_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05)\
		case RAW_ENUM_TYPE::ENUM_VAL06: Result = UEBP_ENUM_TYPE::ENUM_VAL06; break;

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_6_ENTRIES(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_6_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_6_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_BASEINNER_BOTTOM(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL)

#pragma endregion UABTEnumConversion 6 Entries


#pragma region UABTEnumConversion 7 Entries

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_7_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_6_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06)\
			case UEBP_ENUM_TYPE::ENUM_VAL07: Result = RAW_ENUM_TYPE::ENUM_VAL07; break;

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_7_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_6_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06)\
		case RAW_ENUM_TYPE::ENUM_VAL07: Result = UEBP_ENUM_TYPE::ENUM_VAL07; break;

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_7_ENTRIES(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_7_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_7_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_BASEINNER_BOTTOM(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL)

#pragma endregion UABTEnumConversion 7 Entries


#pragma region UABTEnumConversion 8 Entries

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_8_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_7_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07)\
			case UEBP_ENUM_TYPE::ENUM_VAL08: Result = RAW_ENUM_TYPE::ENUM_VAL08; break;

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_8_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_7_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07)\
		case RAW_ENUM_TYPE::ENUM_VAL08: Result = UEBP_ENUM_TYPE::ENUM_VAL08; break;

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_8_ENTRIES(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_8_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_8_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_BASEINNER_BOTTOM(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL)

#pragma endregion UABTEnumConversion 8 Entries


#pragma region UABTEnumConversion 9 Entries

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_9_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_8_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08)\
			case UEBP_ENUM_TYPE::ENUM_VAL09: Result = RAW_ENUM_TYPE::ENUM_VAL09; break;

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_9_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_8_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08)\
		case RAW_ENUM_TYPE::ENUM_VAL09: Result = UEBP_ENUM_TYPE::ENUM_VAL09; break;

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_9_ENTRIES(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_9_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_9_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_BASEINNER_BOTTOM(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL)

#pragma endregion UABTEnumConversion 9 Entries


#pragma region UABTEnumConversion 10 Entries

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_10_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_9_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09)\
			case UEBP_ENUM_TYPE::ENUM_VAL10: Result = RAW_ENUM_TYPE::ENUM_VAL10; break;

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_10_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_9_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09)\
		case RAW_ENUM_TYPE::ENUM_VAL10: Result = UEBP_ENUM_TYPE::ENUM_VAL10; break;


#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_10_ENTRIES(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_10_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_10_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_BASEINNER_BOTTOM(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL)

#pragma endregion UABTEnumConversion 10 Entries


#pragma region UABTEnumConversion 11 Entries

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_11_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_10_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10)\
			case UEBP_ENUM_TYPE::ENUM_VAL11: Result = RAW_ENUM_TYPE::ENUM_VAL11; break;

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_11_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_10_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10)\
		case RAW_ENUM_TYPE::ENUM_VAL11: Result = UEBP_ENUM_TYPE::ENUM_VAL11; break;

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_11_ENTRIES(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_11_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_11_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_BASEINNER_BOTTOM(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL)

#pragma endregion UABTEnumConversion 11 Entries


#pragma region UABTEnumConversion 12 Entries

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_12_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_11_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11)\
			case UEBP_ENUM_TYPE::ENUM_VAL12: Result = RAW_ENUM_TYPE::ENUM_VAL12; break;

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_12_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_11_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11)\
		case RAW_ENUM_TYPE::ENUM_VAL12: Result = UEBP_ENUM_TYPE::ENUM_VAL12; break;

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_12_ENTRIES(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_12_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_12_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_BASEINNER_BOTTOM(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL)

#pragma endregion UABTEnumConversion 12 Entries


#pragma region UABTEnumConversion 13 Entries

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_13_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_12_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12)\
			case UEBP_ENUM_TYPE::ENUM_VAL13: Result = RAW_ENUM_TYPE::ENUM_VAL13; break;

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_13_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_12_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12)\
		case RAW_ENUM_TYPE::ENUM_VAL13: Result = UEBP_ENUM_TYPE::ENUM_VAL13; break;

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_13_ENTRIES(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_13_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_13_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_BASEINNER_BOTTOM(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL)

#pragma endregion UABTEnumConversion 13 Entries


#pragma region UABTEnumConversion 14 Entries

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_14_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_13_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13)\
			case UEBP_ENUM_TYPE::ENUM_VAL14: Result = RAW_ENUM_TYPE::ENUM_VAL14; break;

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_14_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_13_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13)\
		case RAW_ENUM_TYPE::ENUM_VAL14: Result = UEBP_ENUM_TYPE::ENUM_VAL14; break;

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_14_ENTRIES(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_14_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_14_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_BASEINNER_BOTTOM(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL)

#pragma endregion UABTEnumConversion 14 Entries


#pragma region UABTEnumConversion 15 Entries

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_15_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_14_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14)\
			case UEBP_ENUM_TYPE::ENUM_VAL15: Result = RAW_ENUM_TYPE::ENUM_VAL15; break;

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_15_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_14_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14)\
		case RAW_ENUM_TYPE::ENUM_VAL15: Result = UEBP_ENUM_TYPE::ENUM_VAL15; break;

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_15_ENTRIES(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_15_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_15_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_BASEINNER_BOTTOM(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL)

#pragma endregion UABTEnumConversion 15 Entries


#pragma region UABTEnumConversion 16 Entries

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_16_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_15_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15)\
			case UEBP_ENUM_TYPE::ENUM_VAL16: Result = RAW_ENUM_TYPE::ENUM_VAL16; break;

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_16_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_15_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15)\
		case RAW_ENUM_TYPE::ENUM_VAL16: Result = UEBP_ENUM_TYPE::ENUM_VAL16; break;

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_16_ENTRIES(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_16_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_16_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_BASEINNER_BOTTOM(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL)

#pragma endregion UABTEnumConversion 16 Entries


#pragma region UABTEnumConversion 17 Entries

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_17_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_16_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16)\
			case UEBP_ENUM_TYPE::ENUM_VAL17: Result = RAW_ENUM_TYPE::ENUM_VAL17; break;

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_17_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_16_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16)\
		case RAW_ENUM_TYPE::ENUM_VAL17: Result = UEBP_ENUM_TYPE::ENUM_VAL17; break;

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_17_ENTRIES(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_17_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_17_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_BASEINNER_BOTTOM(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL)

#pragma endregion UABTEnumConversion 17 Entries


#pragma region UABTEnumConversion 18 Entries

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_18_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_17_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17)\
			case UEBP_ENUM_TYPE::ENUM_VAL18: Result = RAW_ENUM_TYPE::ENUM_VAL18; break;

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_18_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_17_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17)\
		case RAW_ENUM_TYPE::ENUM_VAL18: Result = UEBP_ENUM_TYPE::ENUM_VAL18; break;

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_18_ENTRIES(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_18_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_18_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_BASEINNER_BOTTOM(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL)

#pragma endregion UABTEnumConversion 18 Entries


#pragma region UABTEnumConversion 19 Entries

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_19_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18,ENUM_VAL19)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_18_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18)\
			case UEBP_ENUM_TYPE::ENUM_VAL19: Result = RAW_ENUM_TYPE::ENUM_VAL19; break;

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_19_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18,ENUM_VAL19)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_18_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18)\
		case RAW_ENUM_TYPE::ENUM_VAL19: Result = UEBP_ENUM_TYPE::ENUM_VAL19; break;

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_19_ENTRIES(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18,ENUM_VAL19)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_19_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18,ENUM_VAL19)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_19_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18,ENUM_VAL19)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_BASEINNER_BOTTOM(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL)

#pragma endregion UABTEnumConversion 19 Entries



#pragma region UABTEnumConversion 20 Entries

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_20_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18,ENUM_VAL19,ENUM_VAL20)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_19_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18,ENUM_VAL19)\
			case UEBP_ENUM_TYPE::ENUM_VAL20: Result = RAW_ENUM_TYPE::ENUM_VAL20; break;

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_20_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18,ENUM_VAL19,ENUM_VAL20)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_19_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18,ENUM_VAL19)\
		case RAW_ENUM_TYPE::ENUM_VAL20: Result = UEBP_ENUM_TYPE::ENUM_VAL20; break;


#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_20_ENTRIES(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18,ENUM_VAL19,ENUM_VAL20)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_20_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18,ENUM_VAL19,ENUM_VAL20)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_20_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18,ENUM_VAL19,ENUM_VAL20)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_BASEINNER_BOTTOM(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL)


#pragma endregion UABTEnumConversion 20 Entries


#pragma region UABTEnumConversion 21 Entries

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_21_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18,ENUM_VAL19,ENUM_VAL20,ENUM_VAL21)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_20_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18,ENUM_VAL19,ENUM_VAL20)\
			case UEBP_ENUM_TYPE::ENUM_VAL21: Result = RAW_ENUM_TYPE::ENUM_VAL21; break;

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_21_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18,ENUM_VAL19,ENUM_VAL20,ENUM_VAL21)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_20_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18,ENUM_VAL19,ENUM_VAL20)\
		case RAW_ENUM_TYPE::ENUM_VAL21: Result = UEBP_ENUM_TYPE::ENUM_VAL21; break;

#define GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_21_ENTRIES(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18,ENUM_VAL19,ENUM_VAL20,ENUM_VAL21)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_21_ENTRIES_BASEINNER_TOP(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18,ENUM_VAL19,ENUM_VAL20,ENUM_VAL21)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_21_ENTRIES_BASEINNER_MIDDLE(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18,ENUM_VAL19,ENUM_VAL20,ENUM_VAL21)\
	GEN_UABTFUNC_SIGNATURE_ENUMCONVERSION_BASEINNER_BOTTOM(UEBP_ENUM_TYPE,RAW_ENUM_TYPE,DEFAULT_ENUM_VAL)

#pragma endregion UABTEnumConversion 21 Entries

#pragma endregion UABT_ENUM_CONVERT