// Copyright(c) 2024 Agora.io. All rights reserved.

#pragma once


#pragma region AGORAENUM_UEENUM_CONVERT - Base

// Base

#pragma region Complete Base Macro Example
//// Complete BASE Macro
//#define AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL) \
//		USTRUCTNAME() :ValueWrapper(UE_ENUM_TYPE::DEFAULT_ENUM_VAL) {}\
//		USTRUCTNAME(UE_ENUM_TYPE Val) :ValueWrapper(Val) {}\
//		USTRUCTNAME(AGORA_ENUM_TYPE val){\
//			switch (val) {\
//				case AGORA_ENUM_TYPE::DEFAULT_ENUM_VAL: ValueWrapper = UE_ENUM_TYPE::DEFAULT_ENUM_VAL; break;\
//				\
//				CONSTRUCTPR_SWITCH_MACROFUNC(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)  \
//				\
//				default: ValueWrapper = UE_ENUM_TYPE::DEFAULT_ENUM_VAL; break;\
//			};\
//		}\
//		void operator = (UE_ENUM_TYPE InValue) {\
//				\
//					ValueWrapper = InValue; \
//		}\
//		AGORA_ENUM_TYPE GetRawValue() const { \
//			switch (ValueWrapper)\
//			{\
//				case UE_ENUM_TYPE::DEFAULT_ENUM_VAL: return  AGORA_ENUM_TYPE::DEFAULT_ENUM_VAL; break;\
//				\
//				GET_RAW_VAL_SWITCH_MACROFUNC()\
//				\
//				default: return  AGORA_ENUM_TYPE::DEFAULT_ENUM_VAL;\
//			}\
//		};
#pragma endregion


#pragma region Original UStruct Example
//USTRUCT(BlueprintType)
//struct EUABT_CAPTURE_BRIGHTNESS_LEVEL_TYPE
//{
//	GENERATED_BODY()
//
//public:
//	// require to call [GetRawValue] method to get the raw value 
//	UPROPERTY(VisibleAnywhere, BlueprintReadWrite, Category = "Agora|EUABT_CAPTURE_BRIGHTNESS_LEVEL_TYPE")
//	EUABT_CAPTURE_BRIGHTNESS_LEVEL_TYPE ValueWrapper = EUABT_CAPTURE_BRIGHTNESS_LEVEL_TYPE::CAPTURE_BRIGHTNESS_LEVEL_INVALID;
//
//	// default 
//	EUABT_CAPTURE_BRIGHTNESS_LEVEL_TYPE() :ValueWrapper(EUABT_CAPTURE_BRIGHTNESS_LEVEL_TYPE::CAPTURE_BRIGHTNESS_LEVEL_INVALID) {}
//
//	EUABT_CAPTURE_BRIGHTNESS_LEVEL_TYPE(EUABT_CAPTURE_BRIGHTNESS_LEVEL_TYPE Val) :ValueWrapper(Val) {}
//	void operator = (EUABT_CAPTURE_BRIGHTNESS_LEVEL_TYPE InValue) {
//		ValueWrapper = InValue;
//	}
//	EUABT_CAPTURE_BRIGHTNESS_LEVEL_TYPE(agora::rtc::CAPTURE_BRIGHTNESS_LEVEL_TYPE Val) {
//		switch (Val) {
//		case  agora::rtc::CAPTURE_BRIGHTNESS_LEVEL_TYPE::CAPTURE_BRIGHTNESS_LEVEL_INVALID:
//			ValueWrapper = EUABT_CAPTURE_BRIGHTNESS_LEVEL_TYPE::CAPTURE_BRIGHTNESS_LEVEL_INVALID;
//			break;
//		case  agora::rtc::CAPTURE_BRIGHTNESS_LEVEL_TYPE::CAPTURE_BRIGHTNESS_LEVEL_NORMAL:
//			ValueWrapper = EUABT_CAPTURE_BRIGHTNESS_LEVEL_TYPE::CAPTURE_BRIGHTNESS_LEVEL_NORMAL;
//			break;
//		case  agora::rtc::CAPTURE_BRIGHTNESS_LEVEL_TYPE::CAPTURE_BRIGHTNESS_LEVEL_BRIGHT:
//			ValueWrapper = EUABT_CAPTURE_BRIGHTNESS_LEVEL_TYPE::CAPTURE_BRIGHTNESS_LEVEL_BRIGHT;
//			break;
//		case  agora::rtc::CAPTURE_BRIGHTNESS_LEVEL_TYPE::CAPTURE_BRIGHTNESS_LEVEL_DARK:
//			ValueWrapper = EUABT_CAPTURE_BRIGHTNESS_LEVEL_TYPE::CAPTURE_BRIGHTNESS_LEVEL_DARK;
//			break;
//		}
//	}
//	agora::rtc::CAPTURE_BRIGHTNESS_LEVEL_TYPE GetRawValue() const {
//		switch (ValueWrapper)
//		{
//		case EUABT_CAPTURE_BRIGHTNESS_LEVEL_TYPE::CAPTURE_BRIGHTNESS_LEVEL_INVALID:
//			return  agora::rtc::CAPTURE_BRIGHTNESS_LEVEL_TYPE::CAPTURE_BRIGHTNESS_LEVEL_INVALID;
//		case EUABT_CAPTURE_BRIGHTNESS_LEVEL_TYPE::CAPTURE_BRIGHTNESS_LEVEL_NORMAL:
//			return agora::rtc::CAPTURE_BRIGHTNESS_LEVEL_TYPE::CAPTURE_BRIGHTNESS_LEVEL_NORMAL;
//		case EUABT_CAPTURE_BRIGHTNESS_LEVEL_TYPE::CAPTURE_BRIGHTNESS_LEVEL_BRIGHT:
//			return agora::rtc::CAPTURE_BRIGHTNESS_LEVEL_TYPE::CAPTURE_BRIGHTNESS_LEVEL_BRIGHT;
//		case EUABT_CAPTURE_BRIGHTNESS_LEVEL_TYPE::CAPTURE_BRIGHTNESS_LEVEL_DARK:
//			return agora::rtc::CAPTURE_BRIGHTNESS_LEVEL_TYPE::CAPTURE_BRIGHTNESS_LEVEL_DARK;
//		default:
//			return  agora::rtc::CAPTURE_BRIGHTNESS_LEVEL_TYPE::CAPTURE_BRIGHTNESS_LEVEL_INVALID;
//		}
//	}
//};
#pragma endregion


// a member variable name in UAgoraEnumConvertToUEEnumStruct
#define AGORA_UE_ENUM_C_VAR_NAME ValueWrapper

#define GET_AGORA_ENUM_VAL_FUNC_NAME GetRawValue

/*
1. default constructor
2. constructor with UE enum val
3. constructor with agora enum val
*/
#define AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_CONSTRUCTOR_SWITCH(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL) \
		USTRUCTNAME() :AGORA_UE_ENUM_C_VAR_NAME(UE_ENUM_TYPE::DEFAULT_ENUM_VAL) {}\
		USTRUCTNAME(UE_ENUM_TYPE Val) :AGORA_UE_ENUM_C_VAR_NAME(Val) {}\
		USTRUCTNAME(AGORA_ENUM_TYPE val){\
			switch (val) {\
				case AGORA_ENUM_TYPE::DEFAULT_ENUM_VAL: AGORA_UE_ENUM_C_VAR_NAME = UE_ENUM_TYPE::DEFAULT_ENUM_VAL; break;\

/*
1. assignment operator overloading
2. get raw agora enum value
*/
#define AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_GETRAWVAL(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
			default: AGORA_UE_ENUM_C_VAR_NAME = UE_ENUM_TYPE::DEFAULT_ENUM_VAL; break;\
			};\
		}\
		void operator = (UE_ENUM_TYPE InValue) {\
				\
					AGORA_UE_ENUM_C_VAR_NAME = InValue; \
		}\
		AGORA_ENUM_TYPE GET_AGORA_ENUM_VAL_FUNC_NAME() const { \
			switch (AGORA_UE_ENUM_C_VAR_NAME)\
			{\
				case UE_ENUM_TYPE::DEFAULT_ENUM_VAL: return  AGORA_ENUM_TYPE::DEFAULT_ENUM_VAL; break;\

#define AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BOTTOM(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
				default: return  AGORA_ENUM_TYPE::DEFAULT_ENUM_VAL;\
			}\
		};

#pragma endregion

#pragma region AGORAENUM_UEENUM_CONVERT 1 Entry

// 1 Entry

#define AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_1_ENTRY(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_CONSTRUCTOR_SWITCH(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_GETRAWVAL(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BOTTOM(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)

#pragma endregion

#pragma region AGORAENUM_UEENUM_CONVERT 2 Entries

// 2 Entries

#define AGORA_CONVERT_TO_UEENUM_EXTRA_1_ENTRY(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02)\
	case AGORA_ENUM_TYPE::ENUM_VAL02: AGORA_UE_ENUM_C_VAR_NAME = UE_ENUM_TYPE::ENUM_VAL02; break;

#define AGORA_CONVERT_TO_AGORAENUM_EXTRA_1_ENTRY(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02)\
	case UE_ENUM_TYPE::ENUM_VAL02: return AGORA_ENUM_TYPE::ENUM_VAL02; break;

#define AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_2_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02)\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_CONSTRUCTOR_SWITCH(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
	\
	AGORA_CONVERT_TO_UEENUM_EXTRA_1_ENTRY(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02)\
	\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_GETRAWVAL(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
	\
	AGORA_CONVERT_TO_AGORAENUM_EXTRA_1_ENTRY(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02)\
	\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BOTTOM(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)

#pragma endregion

#pragma region AGORAENUM_UEENUM_CONVERT 3 Entries

// 3 Entries

#define AGORA_CONVERT_TO_UEENUM_EXTRA_2_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03)\
	AGORA_CONVERT_TO_UEENUM_EXTRA_1_ENTRY(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02)\
	case AGORA_ENUM_TYPE::ENUM_VAL03: AGORA_UE_ENUM_C_VAR_NAME = UE_ENUM_TYPE::ENUM_VAL03; break;

#define AGORA_CONVERT_TO_AGORAENUM_EXTRA_2_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03)\
	AGORA_CONVERT_TO_AGORAENUM_EXTRA_1_ENTRY(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02)\
	case UE_ENUM_TYPE::ENUM_VAL03: return AGORA_ENUM_TYPE::ENUM_VAL03; break;

#define AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_3_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03)\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_CONSTRUCTOR_SWITCH(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
	\
	AGORA_CONVERT_TO_UEENUM_EXTRA_2_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03)\
	\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_GETRAWVAL(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
	\
	AGORA_CONVERT_TO_AGORAENUM_EXTRA_2_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03)\
	\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BOTTOM(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)


#pragma endregion

#pragma region AGORAENUM_UEENUM_CONVERT 4 Entries

// 4 Entries

#define AGORA_CONVERT_TO_UEENUM_EXTRA_3_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04)\
	AGORA_CONVERT_TO_UEENUM_EXTRA_2_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03)\
	case AGORA_ENUM_TYPE::ENUM_VAL04: AGORA_UE_ENUM_C_VAR_NAME = UE_ENUM_TYPE::ENUM_VAL04; break;

#define AGORA_CONVERT_TO_AGORAENUM_EXTRA_3_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04)\
	AGORA_CONVERT_TO_AGORAENUM_EXTRA_2_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03)\
	case UE_ENUM_TYPE::ENUM_VAL04: return AGORA_ENUM_TYPE::ENUM_VAL04; break;

#define AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_4_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04)\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_CONSTRUCTOR_SWITCH(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
	\
	AGORA_CONVERT_TO_UEENUM_EXTRA_3_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04)\
	\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_GETRAWVAL(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
	\
	AGORA_CONVERT_TO_AGORAENUM_EXTRA_3_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04)\
	\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BOTTOM(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)

#pragma endregion

#pragma region AGORAENUM_UEENUM_CONVERT 5 Entries

// 5 Entries

#define AGORA_CONVERT_TO_UEENUM_EXTRA_4_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05)\
    AGORA_CONVERT_TO_UEENUM_EXTRA_3_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04)\
    case AGORA_ENUM_TYPE::ENUM_VAL05: AGORA_UE_ENUM_C_VAR_NAME = UE_ENUM_TYPE::ENUM_VAL05; break;

#define AGORA_CONVERT_TO_AGORAENUM_EXTRA_4_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05)\
    AGORA_CONVERT_TO_AGORAENUM_EXTRA_3_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04)\
    case UE_ENUM_TYPE::ENUM_VAL05: return AGORA_ENUM_TYPE::ENUM_VAL05; break;

#define AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_5_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05)\
    AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_CONSTRUCTOR_SWITCH(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
    \
    AGORA_CONVERT_TO_UEENUM_EXTRA_4_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05)\
    \
    AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_GETRAWVAL(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
    \
    AGORA_CONVERT_TO_AGORAENUM_EXTRA_4_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05)\
    \
    AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BOTTOM(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)


#pragma endregion

#pragma region AGORAENUM_UEENUM_CONVERT 6 Entries

// 6 Entries

#define AGORA_CONVERT_TO_UEENUM_EXTRA_5_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06)\
    AGORA_CONVERT_TO_UEENUM_EXTRA_4_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05)\
    case AGORA_ENUM_TYPE::ENUM_VAL06: AGORA_UE_ENUM_C_VAR_NAME = UE_ENUM_TYPE::ENUM_VAL06; break;

#define AGORA_CONVERT_TO_AGORAENUM_EXTRA_5_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06)\
    AGORA_CONVERT_TO_AGORAENUM_EXTRA_4_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05)\
    case UE_ENUM_TYPE::ENUM_VAL06: return AGORA_ENUM_TYPE::ENUM_VAL06; break;

#define AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_6_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06)\
    AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_CONSTRUCTOR_SWITCH(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
    \
    AGORA_CONVERT_TO_UEENUM_EXTRA_5_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06)\
    \
    AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_GETRAWVAL(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
    \
    AGORA_CONVERT_TO_AGORAENUM_EXTRA_5_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06)\
    \
    AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BOTTOM(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)


#pragma endregion

#pragma region AGORAENUM_UEENUM_CONVERT 7 Entries

// 7 Entries

#define AGORA_CONVERT_TO_UEENUM_EXTRA_6_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07)\
    AGORA_CONVERT_TO_UEENUM_EXTRA_5_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06)\
    case AGORA_ENUM_TYPE::ENUM_VAL07: AGORA_UE_ENUM_C_VAR_NAME = UE_ENUM_TYPE::ENUM_VAL07; break;

#define AGORA_CONVERT_TO_AGORAENUM_EXTRA_6_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07)\
    AGORA_CONVERT_TO_AGORAENUM_EXTRA_5_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06)\
    case UE_ENUM_TYPE::ENUM_VAL07: return AGORA_ENUM_TYPE::ENUM_VAL07; break;

#define AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_7_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07)\
    AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_CONSTRUCTOR_SWITCH(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
    \
    AGORA_CONVERT_TO_UEENUM_EXTRA_6_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07)\
    \
    AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_GETRAWVAL(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
    \
    AGORA_CONVERT_TO_AGORAENUM_EXTRA_6_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07)\
    \
    AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BOTTOM(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)



#pragma endregion

#pragma region AGORAENUM_UEENUM_CONVERT 8 Entries

// 8 Entries

#define AGORA_CONVERT_TO_UEENUM_EXTRA_7_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08)\
    AGORA_CONVERT_TO_UEENUM_EXTRA_6_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07)\
    case AGORA_ENUM_TYPE::ENUM_VAL08: AGORA_UE_ENUM_C_VAR_NAME = UE_ENUM_TYPE::ENUM_VAL08; break;

#define AGORA_CONVERT_TO_AGORAENUM_EXTRA_7_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08)\
    AGORA_CONVERT_TO_AGORAENUM_EXTRA_6_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07)\
    case UE_ENUM_TYPE::ENUM_VAL08: return AGORA_ENUM_TYPE::ENUM_VAL08; break;

#define AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_8_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08)\
    AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_CONSTRUCTOR_SWITCH(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
    \
    AGORA_CONVERT_TO_UEENUM_EXTRA_7_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08)\
    \
    AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_GETRAWVAL(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
    \
    AGORA_CONVERT_TO_AGORAENUM_EXTRA_7_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08)\
    \
    AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BOTTOM(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)


#pragma endregion

#pragma region AGORAENUM_UEENUM_CONVERT 9 Entries

// 9 Entries

#define AGORA_CONVERT_TO_UEENUM_EXTRA_8_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09)\
    AGORA_CONVERT_TO_UEENUM_EXTRA_7_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08)\
    case AGORA_ENUM_TYPE::ENUM_VAL09: AGORA_UE_ENUM_C_VAR_NAME = UE_ENUM_TYPE::ENUM_VAL09; break;

#define AGORA_CONVERT_TO_AGORAENUM_EXTRA_8_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09)\
    AGORA_CONVERT_TO_AGORAENUM_EXTRA_7_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08)\
    case UE_ENUM_TYPE::ENUM_VAL09: return AGORA_ENUM_TYPE::ENUM_VAL09; break;

#define AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_9_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09)\
    AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_CONSTRUCTOR_SWITCH(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
    \
    AGORA_CONVERT_TO_UEENUM_EXTRA_8_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09)\
    \
    AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_GETRAWVAL(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
    \
    AGORA_CONVERT_TO_AGORAENUM_EXTRA_8_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09)\
    \
    AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BOTTOM(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)

#pragma endregion

#pragma region AGORAENUM_UEENUM_CONVERT 10 Entries

// 10 Entries

#define AGORA_CONVERT_TO_UEENUM_EXTRA_9_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10)\
    AGORA_CONVERT_TO_UEENUM_EXTRA_8_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09)\
    case AGORA_ENUM_TYPE::ENUM_VAL10: AGORA_UE_ENUM_C_VAR_NAME = UE_ENUM_TYPE::ENUM_VAL10; break;

#define AGORA_CONVERT_TO_AGORAENUM_EXTRA_9_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10)\
    AGORA_CONVERT_TO_AGORAENUM_EXTRA_8_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09)\
    case UE_ENUM_TYPE::ENUM_VAL10: return AGORA_ENUM_TYPE::ENUM_VAL10; break;

#define AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_10_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10)\
    AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_CONSTRUCTOR_SWITCH(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
    \
    AGORA_CONVERT_TO_UEENUM_EXTRA_9_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10)\
    \
    AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_GETRAWVAL(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
    \
    AGORA_CONVERT_TO_AGORAENUM_EXTRA_9_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10)\
    \
    AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BOTTOM(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)

#pragma endregion

#pragma region AGORAENUM_UEENUM_CONVERT 11 Entries

// 11 Entries

#define AGORA_CONVERT_TO_UEENUM_EXTRA_10_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11)\
    AGORA_CONVERT_TO_UEENUM_EXTRA_9_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10)\
    case AGORA_ENUM_TYPE::ENUM_VAL11: AGORA_UE_ENUM_C_VAR_NAME = UE_ENUM_TYPE::ENUM_VAL11; break;

#define AGORA_CONVERT_TO_AGORAENUM_EXTRA_10_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11)\
    AGORA_CONVERT_TO_AGORAENUM_EXTRA_9_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10)\
    case UE_ENUM_TYPE::ENUM_VAL11: return AGORA_ENUM_TYPE::ENUM_VAL11; break;

#define AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_11_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11)\
    AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_CONSTRUCTOR_SWITCH(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
    \
    AGORA_CONVERT_TO_UEENUM_EXTRA_10_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11)\
    \
    AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_GETRAWVAL(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
    \
    AGORA_CONVERT_TO_AGORAENUM_EXTRA_10_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11)\
    \
    AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BOTTOM(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)

#pragma endregion

#pragma region AGORAENUM_UEENUM_CONVERT 12 Entries

// 12 Entries

#define AGORA_CONVERT_TO_UEENUM_EXTRA_11_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12)\
    AGORA_CONVERT_TO_UEENUM_EXTRA_10_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11)\
    case AGORA_ENUM_TYPE::ENUM_VAL12: AGORA_UE_ENUM_C_VAR_NAME = UE_ENUM_TYPE::ENUM_VAL12; break;

#define AGORA_CONVERT_TO_AGORAENUM_EXTRA_11_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12)\
    AGORA_CONVERT_TO_AGORAENUM_EXTRA_10_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11)\
    case UE_ENUM_TYPE::ENUM_VAL12: return AGORA_ENUM_TYPE::ENUM_VAL12; break;

#define AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_12_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12)\
    AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_CONSTRUCTOR_SWITCH(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
    \
    AGORA_CONVERT_TO_UEENUM_EXTRA_11_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12)\
    \
    AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_GETRAWVAL(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
    \
    AGORA_CONVERT_TO_AGORAENUM_EXTRA_11_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12)\
    \
    AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BOTTOM(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)

#pragma endregion

#pragma region AGORAENUM_UEENUM_CONVERT 13 Entries

// 13 Entries

#define AGORA_CONVERT_TO_UEENUM_EXTRA_12_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13)\
	AGORA_CONVERT_TO_UEENUM_EXTRA_11_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12)\
	case AGORA_ENUM_TYPE::ENUM_VAL13: AGORA_UE_ENUM_C_VAR_NAME = UE_ENUM_TYPE::ENUM_VAL13; break;

#define AGORA_CONVERT_TO_AGORAENUM_EXTRA_12_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13)\
	AGORA_CONVERT_TO_AGORAENUM_EXTRA_11_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12)\
	case UE_ENUM_TYPE::ENUM_VAL13: return AGORA_ENUM_TYPE::ENUM_VAL13; break;

#define AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_13_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13)\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_CONSTRUCTOR_SWITCH(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
	\
	AGORA_CONVERT_TO_UEENUM_EXTRA_12_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13)\
	\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_GETRAWVAL(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
	\
	AGORA_CONVERT_TO_AGORAENUM_EXTRA_12_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13)\
	\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BOTTOM(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)

#pragma endregion

#pragma region AGORAENUM_UEENUM_CONVERT 14 Entries

// 14 Entries

#define AGORA_CONVERT_TO_UEENUM_EXTRA_13_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14)\
	AGORA_CONVERT_TO_UEENUM_EXTRA_12_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13)\
	case AGORA_ENUM_TYPE::ENUM_VAL14: AGORA_UE_ENUM_C_VAR_NAME = UE_ENUM_TYPE::ENUM_VAL14; break;

#define AGORA_CONVERT_TO_AGORAENUM_EXTRA_13_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14)\
	AGORA_CONVERT_TO_AGORAENUM_EXTRA_12_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13)\
	case UE_ENUM_TYPE::ENUM_VAL14: return AGORA_ENUM_TYPE::ENUM_VAL14; break;

#define AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_14_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14)\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_CONSTRUCTOR_SWITCH(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
	\
	AGORA_CONVERT_TO_UEENUM_EXTRA_13_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14)\
	\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_GETRAWVAL(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
	\
	AGORA_CONVERT_TO_AGORAENUM_EXTRA_13_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14)\
	\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BOTTOM(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)

#pragma endregion

#pragma region AGORAENUM_UEENUM_CONVERT 15 Entries

// 15 Entries

#define AGORA_CONVERT_TO_UEENUM_EXTRA_14_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15)\
	AGORA_CONVERT_TO_UEENUM_EXTRA_13_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14)\
	case AGORA_ENUM_TYPE::ENUM_VAL15: AGORA_UE_ENUM_C_VAR_NAME = UE_ENUM_TYPE::ENUM_VAL15; break;

#define AGORA_CONVERT_TO_AGORAENUM_EXTRA_14_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15)\
	AGORA_CONVERT_TO_AGORAENUM_EXTRA_13_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14)\
	case UE_ENUM_TYPE::ENUM_VAL15: return AGORA_ENUM_TYPE::ENUM_VAL15; break;

#define AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_15_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15)\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_CONSTRUCTOR_SWITCH(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
	\
	AGORA_CONVERT_TO_UEENUM_EXTRA_14_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15)\
	\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_GETRAWVAL(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
	\
	AGORA_CONVERT_TO_AGORAENUM_EXTRA_14_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15)\
	\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BOTTOM(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)

#pragma endregion

#pragma region AGORAENUM_UEENUM_CONVERT 16 Entries

// 16 Entries

#define AGORA_CONVERT_TO_UEENUM_EXTRA_15_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16)\
	AGORA_CONVERT_TO_UEENUM_EXTRA_14_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15)\
	case AGORA_ENUM_TYPE::ENUM_VAL16: AGORA_UE_ENUM_C_VAR_NAME = UE_ENUM_TYPE::ENUM_VAL16; break;

#define AGORA_CONVERT_TO_AGORAENUM_EXTRA_15_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16)\
	AGORA_CONVERT_TO_AGORAENUM_EXTRA_14_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15)\
	case UE_ENUM_TYPE::ENUM_VAL16: return AGORA_ENUM_TYPE::ENUM_VAL16; break;

#define AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_16_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16)\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_CONSTRUCTOR_SWITCH(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
	\
	AGORA_CONVERT_TO_UEENUM_EXTRA_15_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16)\
	\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_GETRAWVAL(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
	\
	AGORA_CONVERT_TO_AGORAENUM_EXTRA_15_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16)\
	\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BOTTOM(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)

#pragma endregion

#pragma region AGORAENUM_UEENUM_CONVERT 17 Entries

// 17 Entries

#define AGORA_CONVERT_TO_UEENUM_EXTRA_16_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17)\
	AGORA_CONVERT_TO_UEENUM_EXTRA_15_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16)\
	case AGORA_ENUM_TYPE::ENUM_VAL17: AGORA_UE_ENUM_C_VAR_NAME = UE_ENUM_TYPE::ENUM_VAL17; break;

#define AGORA_CONVERT_TO_AGORAENUM_EXTRA_16_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17)\
	AGORA_CONVERT_TO_AGORAENUM_EXTRA_15_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16)\
	case UE_ENUM_TYPE::ENUM_VAL17: return AGORA_ENUM_TYPE::ENUM_VAL17; break;

#define AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_17_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17)\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_CONSTRUCTOR_SWITCH(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
	\
	AGORA_CONVERT_TO_UEENUM_EXTRA_16_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17)\
	\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_GETRAWVAL(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
	\
	AGORA_CONVERT_TO_AGORAENUM_EXTRA_16_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17)\
	\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BOTTOM(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)

#pragma endregion

#pragma region AGORAENUM_UEENUM_CONVERT 18 Entries

// 18 Entries

#define AGORA_CONVERT_TO_UEENUM_EXTRA_17_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18)\
	AGORA_CONVERT_TO_UEENUM_EXTRA_16_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17)\
	case AGORA_ENUM_TYPE::ENUM_VAL18: AGORA_UE_ENUM_C_VAR_NAME = UE_ENUM_TYPE::ENUM_VAL18; break;

#define AGORA_CONVERT_TO_AGORAENUM_EXTRA_17_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18)\
	AGORA_CONVERT_TO_AGORAENUM_EXTRA_16_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17)\
	case UE_ENUM_TYPE::ENUM_VAL18: return AGORA_ENUM_TYPE::ENUM_VAL18; break;

#define AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_18_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18)\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_CONSTRUCTOR_SWITCH(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
	\
	AGORA_CONVERT_TO_UEENUM_EXTRA_17_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18)\
	\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_GETRAWVAL(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
	\
	AGORA_CONVERT_TO_AGORAENUM_EXTRA_17_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18)\
	\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BOTTOM(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)

#pragma endregion

#pragma region AGORAENUM_UEENUM_CONVERT 19 Entries

// 19 Entries

#define AGORA_CONVERT_TO_UEENUM_EXTRA_18_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18,ENUM_VAL19)\
	AGORA_CONVERT_TO_UEENUM_EXTRA_17_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18)\
	case AGORA_ENUM_TYPE::ENUM_VAL19: AGORA_UE_ENUM_C_VAR_NAME = UE_ENUM_TYPE::ENUM_VAL19; break;

#define AGORA_CONVERT_TO_AGORAENUM_EXTRA_18_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18,ENUM_VAL19)\
	AGORA_CONVERT_TO_AGORAENUM_EXTRA_17_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18)\
	case UE_ENUM_TYPE::ENUM_VAL19: return AGORA_ENUM_TYPE::ENUM_VAL19; break;

#define AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_19_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18,ENUM_VAL19)\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_CONSTRUCTOR_SWITCH(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
	\
	AGORA_CONVERT_TO_UEENUM_EXTRA_18_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18,ENUM_VAL19)\
	\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_GETRAWVAL(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
	\
	AGORA_CONVERT_TO_AGORAENUM_EXTRA_18_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18,ENUM_VAL19)\
	\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BOTTOM(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)

#pragma endregion

#pragma region AGORAENUM_UEENUM_CONVERT 20 Entries

// 20 Entries

#define AGORA_CONVERT_TO_UEENUM_EXTRA_19_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18,ENUM_VAL19,ENUM_VAL20)\
	AGORA_CONVERT_TO_UEENUM_EXTRA_18_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18,ENUM_VAL19)\
	case AGORA_ENUM_TYPE::ENUM_VAL20: AGORA_UE_ENUM_C_VAR_NAME = UE_ENUM_TYPE::ENUM_VAL20; break;

#define AGORA_CONVERT_TO_AGORAENUM_EXTRA_19_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18,ENUM_VAL19,ENUM_VAL20)\
	AGORA_CONVERT_TO_AGORAENUM_EXTRA_18_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18,ENUM_VAL19)\
	case UE_ENUM_TYPE::ENUM_VAL20: return AGORA_ENUM_TYPE::ENUM_VAL20; break;

#define AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_20_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18,ENUM_VAL19,ENUM_VAL20)\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_CONSTRUCTOR_SWITCH(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
	\
	AGORA_CONVERT_TO_UEENUM_EXTRA_19_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18,ENUM_VAL19,ENUM_VAL20)\
	\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_GETRAWVAL(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
	\
	AGORA_CONVERT_TO_AGORAENUM_EXTRA_19_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18,ENUM_VAL19,ENUM_VAL20)\
	\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BOTTOM(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)

#pragma endregion

#pragma region AGORAENUM_UEENUM_CONVERT 21 Entries

// 21 Entries

#define AGORA_CONVERT_TO_UEENUM_EXTRA_20_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18,ENUM_VAL19,ENUM_VAL20,ENUM_VAL21)\
	AGORA_CONVERT_TO_UEENUM_EXTRA_19_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18,ENUM_VAL19,ENUM_VAL20)\
	case AGORA_ENUM_TYPE::ENUM_VAL21: AGORA_UE_ENUM_C_VAR_NAME = UE_ENUM_TYPE::ENUM_VAL21; break;

#define AGORA_CONVERT_TO_AGORAENUM_EXTRA_20_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18,ENUM_VAL19,ENUM_VAL20,ENUM_VAL21)\
	AGORA_CONVERT_TO_AGORAENUM_EXTRA_19_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18,ENUM_VAL19,ENUM_VAL20)\
	case UE_ENUM_TYPE::ENUM_VAL21: return AGORA_ENUM_TYPE::ENUM_VAL21; break;

#define AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_21_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18,ENUM_VAL19,ENUM_VAL20,ENUM_VAL21)\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_CONSTRUCTOR_SWITCH(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
	\
	AGORA_CONVERT_TO_UEENUM_EXTRA_20_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18,ENUM_VAL19,ENUM_VAL20,ENUM_VAL21)\
	\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BEFORE_GETRAWVAL(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)\
	\
	AGORA_CONVERT_TO_AGORAENUM_EXTRA_20_ENTRIES(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,ENUM_VAL02,ENUM_VAL03,ENUM_VAL04,ENUM_VAL05,ENUM_VAL06,ENUM_VAL07,ENUM_VAL08,ENUM_VAL09,ENUM_VAL10,ENUM_VAL11,ENUM_VAL12,ENUM_VAL13,ENUM_VAL14,ENUM_VAL15,ENUM_VAL16,ENUM_VAL17,ENUM_VAL18,ENUM_VAL19,ENUM_VAL20,ENUM_VAL21)\
	\
	AGORA_CREATE_UEENUM_CONVERT_STRUCT_INNER_BASE_BOTTOM(USTRUCTNAME,AGORA_ENUM_TYPE,UE_ENUM_TYPE,DEFAULT_ENUM_VAL)

#pragma endregion